import mtg

assert(mtg.Faction.who_can_play('red') == {'chaos', 'rakdos', 'red', 'temur', 'gruul', 'aggression', 'grixis', 'artifice', 'boros', 'jeskai', 'izzet', 'mardu', 'jund', 'altruism', 'naya'})
assert(mtg.Faction.who_can_play('orzhov') == {'chaos', 'abzan', 'orzhov', 'aggression', 'artifice', 'esper', 'mardu', 'growth'})
assert(mtg.Faction.who_can_play('aggression') == {'aggression'})
assert(mtg.Faction.who_can_play('grixis') == {'artifice', 'chaos', 'grixis'})
assert(mtg.Faction.who_can_play('jeskai') == {'altruism', 'jeskai', 'artifice'})
assert(mtg.Faction.who_can_play('esper') == {'esper', 'growth', 'artifice'})
assert(mtg.Faction.who_can_play('izzet') == {'temur', 'grixis', 'artifice', 'jeskai', 'izzet', 'altruism'})
assert(mtg.Faction.who_can_play('mardu') == {'artifice', 'aggression', 'mardu'})
assert(mtg.Faction.who_can_play('dimir') == {'chaos', 'sultai', 'grixis', 'artifice', 'esper', 'growth', 'dimir'})
assert(mtg.Faction.who_can_play('growth') == {'growth'})
assert(mtg.Faction.who_can_play('chaos') == {'chaos'})
assert(mtg.Faction.who_can_play('white') == {'azorius', 'white', 'orzhov', 'bant', 'selesnya', 'abzan', 'aggression', 'artifice', 'boros', 'jeskai', 'esper', 'mardu', 'altruism', 'naya', 'growth'})
assert(mtg.Faction.who_can_play('sultai') == {'sultai', 'chaos', 'growth'})
assert(mtg.Faction.who_can_play('temur') == {'temur', 'chaos', 'altruism'})
assert(mtg.Faction.who_can_play('abzan') == {'abzan', 'aggression', 'growth'})
assert(mtg.Faction.who_can_play('bant') == {'altruism', 'bant', 'growth'})
assert(mtg.Faction.who_can_play('golgari') == {'chaos', 'sultai', 'abzan', 'aggression', 'golgari', 'jund', 'growth'})
assert(mtg.Faction.who_can_play('altruism') == {'altruism'})
assert(mtg.Faction.who_can_play('naya') == {'altruism', 'naya', 'aggression'})
assert(mtg.Faction.who_can_play('azorius') == {'azorius', 'bant', 'artifice', 'jeskai', 'esper', 'altruism', 'growth'})
assert(mtg.Faction.who_can_play('simic') == {'simic', 'sultai', 'temur', 'bant', 'altruism', 'growth'})
assert(mtg.Faction.who_can_play('rakdos') == {'rakdos', 'aggression', 'grixis', 'artifice', 'mardu', 'jund'})
assert(mtg.Faction.who_can_play('black') == {'chaos', 'rakdos', 'black', 'sultai', 'orzhov', 'abzan', 'aggression', 'grixis', 'golgari', 'artifice', 'esper', 'mardu', 'jund', 'dimir', 'growth'})
assert(mtg.Faction.who_can_play('gruul') == {'chaos', 'temur', 'gruul', 'aggression', 'jund', 'altruism', 'naya'})
assert(mtg.Faction.who_can_play('selesnya') == {'chaos', 'abzan', 'selesnya', 'bant', 'aggression', 'altruism', 'naya', 'growth'})
assert(mtg.Faction.who_can_play('artifice') == {'artifice'})
assert(mtg.Faction.who_can_play('blue') == {'azorius', 'chaos', 'simic', 'sultai', 'temur', 'bant', 'grixis', 'artifice', 'blue', 'jeskai', 'esper', 'izzet', 'altruism', 'dimir', 'growth'})
assert(mtg.Faction.who_can_play('green') == {'chaos', 'simic', 'sultai', 'temur', 'gruul', 'abzan', 'bant', 'selesnya', 'aggression', 'golgari', 'green', 'jund', 'altruism', 'naya', 'growth'})
assert(mtg.Faction.who_can_play('boros') == {'aggression', 'artifice', 'boros', 'jeskai', 'mardu', 'altruism', 'naya'})
assert(mtg.Faction.who_can_play('jund') == {'jund', 'chaos', 'aggression'})
assert(mtg.Faction.who_can_play('{8}{C}{C}') == set())
assert(mtg.Faction.who_can_play('{1}{P/C}') == frozenset({'red', 'orzhov', 'aggression', 'grixis', 'jeskai', 'esper', 'izzet', 'mardu', 'dimir', 'growth', 'chaos', 'white', 'sultai', 'temur', 'abzan', 'bant', 'golgari', 'altruism', 'naya', 'azorius', 'simic', 'rakdos', 'black', 'gruul', 'selesnya', 'artifice', 'blue', 'green', 'boros', 'jund'}))
